// genreadme assembles README.md (English) and README.zh-TW.md (Traditional
// Chinese) from the documentation chapters. Single source of truth:
// docs/<lang>/{overview,install,quickstart}.md. Run from the repository root:
//
//	go run ./scripts/genreadme
//
// Transformations applied to each chapter:
//   - headings are demoted one level; the chapter title becomes "## <letter>. …"
//   - "→ next chapter" navigation lines are dropped
//   - links to other doc pages are rewritten to the documentation site
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const site = "https://ingsquared99.github.io/agent-sync/#"

var chapters = []struct{ file, letter string }{
	{"overview", "A"},
	{"install", "B"},
	{"quickstart", "C"},
}

// ](xxx.md) or ](xxx.md#anchor) → link into the docs site (anchors dropped:
// the site uses its own anchor format)
var mdLink = regexp.MustCompile(`\]\(([a-z]+)\.md(?:#[^)]*)?\)`)

type language struct {
	dir     string // docs subdirectory
	out     string // output README path
	header  string
	deeper  string // the "going deeper" section
	navDrop string // prefix of chapter-navigation lines to drop
}

func main() {
	// GitHub collapses consecutive blank lines, so real vertical breathing
	// room between chapters needs <br> plus a horizontal rule.
	const chapterSep = "\n<br>\n\n---\n\n"
	for _, l := range languages {
		var b strings.Builder
		b.WriteString(l.header)
		for _, ch := range chapters {
			raw, err := os.ReadFile(filepath.Join("docs", l.dir, ch.file+".md"))
			if err != nil {
				fmt.Fprintln(os.Stderr, "genreadme:", err)
				os.Exit(1)
			}
			b.WriteString(transform(string(raw), l, ch.letter))
			b.WriteString(chapterSep)
		}
		b.WriteString(l.deeper)
		if err := os.WriteFile(l.out, []byte(b.String()), 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "genreadme:", err)
			os.Exit(1)
		}
		fmt.Println("wrote", l.out)
	}
}

func transform(raw string, l language, letter string) string {
	lines := strings.Split(raw, "\n")
	var out []string
	inCode := false
	titled := false
	for _, ln := range lines {
		if strings.HasPrefix(strings.TrimSpace(ln), "```") {
			inCode = !inCode
			out = append(out, ln)
			continue
		}
		if inCode {
			out = append(out, ln)
			continue
		}
		if strings.HasPrefix(ln, l.navDrop) { // "→ 下一章…" / "→ Next chapter…"
			continue
		}
		if strings.HasPrefix(ln, "# ") && !titled {
			ln = "## " + letter + ". " + strings.TrimPrefix(ln, "# ")
			titled = true
		} else if strings.HasPrefix(ln, "## ") {
			// extra breathing room before each in-chapter section
			out = append(out, "<br>", "")
			ln = "#" + ln
		} else if strings.HasPrefix(ln, "#") {
			ln = "#" + ln // demote one level
		}
		out = append(out, ln)
	}
	s := strings.Join(out, "\n")
	s = mdLink.ReplaceAllString(s, "]("+site+"/"+l.dir+"/$1)")
	return strings.TrimSpace(s) + "\n"
}

const badges = "[![Release](https://img.shields.io/github/v/release/IngSquared99/agent-sync)](https://github.com/IngSquared99/agent-sync/releases)\n" +
	"[![License: MIT](https://img.shields.io/badge/License-MIT-blue.svg)](LICENSE)\n"

var languages = []language{
	{
		dir:     "en",
		out:     "README.md",
		navDrop: "→ ",
		header: "<!-- AUTO-GENERATED by scripts/genreadme from docs/en/ — do not edit by hand. -->\n\n" +
			"# agsy (agent-sync)\n\n" + badges + "\n" +
			"> Merge & mount tool for multi-source AI instruction files: one set of sources, synced to Claude Code, Codex, Antigravity, and more.\n\n" +
			"**[📘 Full documentation](" + site + "/en/)** ｜ [繁體中文 README](README.zh-TW.md)\n\n---\n\n",
		deeper: "## D. Going deeper\n\n" +
			"Everything beyond installation and the quick start lives on the documentation site:\n\n" +
			"| Topic | Covers |\n|-------|--------|\n" +
			"| [Configuration](" + site + "/en/config) | every agsy.yaml field, with the safety rules |\n" +
			"| [Command Reference](" + site + "/en/commands) | per-command details and situations |\n" +
			"| [Adapters](" + site + "/en/adapters) | built-in tool presets and custom mounts |\n" +
			"| [Scenario Guide](" + site + "/en/scenarios) | apply / promote behavior in every situation |\n" +
			"| [FAQ](" + site + "/en/faq) | common questions from the user's point of view |\n",
	},
	{
		dir:     "zh-TW",
		out:     "README.zh-TW.md",
		navDrop: "→ ",
		header: "<!-- 本檔由 scripts/genreadme 自動組裝，內容來源為 docs/zh-TW/ — 請勿手動編輯。 -->\n\n" +
			"# agsy（agent-sync）\n\n" + badges + "\n" +
			"> 多來源 AI 指令檔的合併與掛載工具：一份來源，同步 Claude Code、Codex、Antigravity 等多個 AI 工具。\n\n" +
			"**[📘 完整說明文件](" + site + "/zh-TW/)** ｜ [English README](README.md)\n\n---\n\n",
		deeper: "## D. 深入了解\n\n" +
			"安裝與快速上手之外的完整教學都在說明文件站：\n\n" +
			"| 主題 | 內容 |\n|------|------|\n" +
			"| [設定檔 agsy.yaml](" + site + "/zh-TW/config) | 每個欄位的完整說明與安全規則 |\n" +
			"| [指令說明](" + site + "/zh-TW/commands) | 各指令細節與使用情境 |\n" +
			"| [適配器](" + site + "/zh-TW/adapters) | 內建工具範本與自訂掛載 |\n" +
			"| [情境全覽](" + site + "/zh-TW/scenarios) | apply / promote 在每種情境下的行為 |\n" +
			"| [Q&A 常見問題](" + site + "/zh-TW/faq) | 以使用者角度整理的常見問題 |\n",
	},
}
